apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/ollama-no-gpu.yaml
  - path: patches/postgres-upstream.json
    target:
      kind: Deployment
      name: postgres
